In [1]:
import numpy as np

In [2]:
tab = np.array([1,2])

In [3]:
tab

array([1, 2])

In [4]:
t = tab.tolist()

In [5]:
t

[1, 2]

In [6]:
a = np.array([(1, 2), (3, 4), (5,6)])
a.shape #it returns (3,2) where 3 number of lines, and 2 number of columns.

(3, 2)

In [10]:
a.shape[1]


2

In [13]:
for x in a:
    print(x[1])
    

2
4
6


In [23]:
a  =np.array([0,0,0,0,1,0,0,0,44,66,5,7])


In [22]:
a.reshape(3,4)

array([[ 0,  0,  0,  0],
       [ 1,  0,  0,  0],
       [44, 66,  5,  7]])

In [24]:
a  =np.array([0,0,0,0,1,0,0,0,44])

In [27]:
a.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)

In [32]:
a = np.array([[88,1,2],[3,4,5],[6,7,8]])


In [35]:
a[0,0]

88

In [36]:
a[0,2]

2

In [37]:
a[1,0]

3

In [38]:
a[1,1]

4

Array Slicing in NumPy
Since we have an array with 3 rows and 3 columns, we start with 0 and end with 2 for column/row numbers.

Row selection
This is how we select the second row:

In [39]:
a = np.array([[88,1,2],[3,4,5],[6,7,8]])


In [49]:
#Row selection This is how we select the second row:

print(a[1,:1])

[3]


In [51]:
print(a[1,:3])

[3 4 5]


In [52]:
print(a[1,1:])

[4 5]


In [55]:
print(a[1,:1])

[3]


In [46]:
print(a[:,0])

[88  3  6]


Column selection
This is how we select the last column:



In [66]:
#This is how we select the last column:

print(a[:, 2])


[2 5 8]


A is an array. How can we select the first and third column?

In [67]:
A = np.array([[0,1,2],[3,4,5]])

In [68]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
A[:,[0]]

array([[0],
       [3]])